services:

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: node-server
    ports:
      - "5000:5000"
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: react-client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongo-data:
